# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Memoir"
license = "MIT"
licenselink = "https://github.com/tthseus/memoir-theme/blob/main/LICENSE"
description = "A Hugo theme"
homepage = "https://github.com/tthseus/memoir-theme"
tags = ["Hugo", "theme", "blog"]
features = []
min_version = "0.0.0"
summaryLength = 40
assetDir = "static"
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "RSS"]
[params]
  css = ["css/style.css"]
  
[author]
  name = "Theseus"
  homepage = "tthseus.github.io"
