baseURL = "https://example.com"
languageCode = "en-us"
title = "Stuff"
theme = "memoir-theme"

UglifyURLs = true
assetDir = "static"
CanonifyURLs = true
summaryLength = 40
[outputs]
    home = ["HTML", "JSON", "RSS"]

[taxonomies]
   tag = "tags"

[permalinks]
    post = "/post/:filename"
    page = "/:filename"
    project = "/project/:filename"
    blog = "/blog/:slug"

[[menu.main]]
  name = "Home"
  url = "/"

[[menu.main]]
  name = "About"
  url = "/about"

[[menu.main]]
  name = "Blog"
  url = "/post"

[[menu.main]]
name = "Search"
url = "/search"

[[menu.footer]]
  name = "About"
  url = "/about"

[[menu.footer]]
  name = "Privacy"
  url = "/privacy"

Paginate = 4